[build]
incremental = true
#target = "wasm32-unknown-unknown"

[cargo-new]
vcs = "git"
email = "someone@ekgf.org"

# Add this section because IntelliJ rust plugin does not
# support the "sparse" protocol very well (as opposed to "git" protocol)
[registries.crates-io]
protocol = "git"

[net]
git-fetch-with-cli = true   # use the `git` executable for git operations

[patch.crates-io]
#ekg-error = { path = "../ekg-rs/crate/ekg-error" }
#ekg-identifier = { path = "../ekg-rs/crate/ekg-identifier" }
#ekg-metadata = { path = "../ekg-rs/crate/ekg-metadata" }
#ekg-sparql = { path = "../ekg-rs/crate/ekg-sparql" }
#ekg-util = { path = "../ekg-rs/crate/ekg-util" }

[term]
color = "always"

